"""add trace fields to telemetry events

Revision ID: c0ebede2393f
Revises: ce12331ef2cd
Create Date: 2026-10-05 12:14:23.170975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ebede2393f'
down_revision: Union[str, Sequence[str], None] = 'ce12331ef2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_events', sa.Column('operation_name', sa.String(length=255), nullable=True))
    op.add_column('telemetry_events', sa.Column('duration_ms', sa.Float(), nullable=True))
    op.add_column('telemetry_events', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_events', 'status')
    op.drop_column('telemetry_events', 'duration_ms')
    op.drop_column('telemetry_events', 'operation_name')
    # ### end Alembic commands ###
